name: "Get Droplet IPs"
description: "Get the IPs to deploy to using tags"
inputs:
  digital-ocean-key:
    description: "The API KEY for DO"
    required: true
  tag:
    description: The tag of the servers to fetch
    required: true
  network_type:
    description: public or private
    default: public

outputs:
  server_ips: # id of output
    description: "The IPs that match the provided tags"
runs:
  using: "node16"
  main: "index.js"
